apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicalrepresentativeschedule-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MedicalRepresentativeSchedule
  template:
    metadata:
      labels:
        app: MedicalRepresentativeSchedule
    spec:
      containers:
      - name: medicalrepschedulerepos
        image: medicinesupplycr.azurecr.io/medicalrepschedulerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: pmsmsecret

---
apiVersion: v1
kind: Service
metadata:
  name: medicalrepresentativeschedule
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MedicalRepresentativeSchedule
